name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0-dev.3
  flutter_localizations:
    sdk: flutter
  form_builder_extra_fields:
    path: ../
  form_builder_validators: ^9.0.0-dev.2

dependency_overrides:
  intl: 0.18.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true