name: form_builder_extra_fields
description: Additional ready-made form input fields for flutter_form_builder package
version: 10.1.0
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/issues
homepage: https://github.com/flutter-form-builder-ecosystem
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields
funding:
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_colorpicker: ^1.1.0
  dropdown_search: ^5.0.6
  signature: ^5.4.0
  intl: ^0.18.1
  flutter_typeahead: ^4.7.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
