name: form_builder_extra_fields
description: Additional ready-made form input fields for flutter_form_builder package
version: 8.1.0
homepage: https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.3.1
  flutter_chips_input: ^2.0.0
  flutter_colorpicker: ^1.0.3
  dropdown_search: ^4.0.1
  signature: ^5.0.1
  flutter_touch_spin: ^2.0.0-nullsafety.1
  intl: ^0.17.0
  flutter_typeahead: ^4.0.0
  flutter_datetime_picker_bdaya: ^2.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
