name: form_builder_extra_fields
description: Additional ready-made form input fields for flutter_form_builder package
version: 11.1.0
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/issues
homepage: https://github.com/flutter-form-builder-ecosystem
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields
topics: 
  - form
  - forms
funding:
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.6.0
  flutter_colorpicker: ^1.1.0
  dropdown_search: ^5.0.6
  signature: ^5.5.0
  intl: ^0.19.0
  flutter_typeahead: ^5.2.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ">=5.0.0 <6.0.0"
  flutter_test:
    sdk: flutter
